id: P40A900A0
initial_creation_type: ocr
source_metadata:
  volumes:
    1c62262d287c42408f83de13327bc406:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: དབུ་མའི་རྒྱན་གྱི་འགྲེལ་པ།
      total_pages: 1557
      volume_number: 62
